### PR TITLE
Improving ForkJoin usage for better performance

### PR DESCRIPTION
**Pull request by gustavopinto**
Hi, I’m a PhD student doing research on ForkJoin usage, and I found that your code can be improved for better performance and energy efficiency.

Using this modification, there is no need to create new List<String> classes instances during the ForkJoin recursive operation. It will save you some memory, time, and energy consumption.

### CODE REVIEW

**Comment by gustavopinto** [comment]
Hi @cbellone, do you think the refactoring is useful? Do you have any plan to merge it? 

Thanks.

**Comment by cbellone** [comment]
Hi @gustavopinto, 

many thanks for your PR and sorry for the late answer.
Yes, I think that your idea should improve the performances. I added a couple of comments on your code. I think that it doesn't work as it is.
As soon as we agree on the implementation, I will definitely merge your PR

thank you very much
Celestino

**Comment by gustavopinto** [comment]
hi @cbellone, I fixed two of your comments, but I didn't get what you mean by "this constructor should call the other one with 0, classes.size() and not vice versa". Can you explain it to me?

**Comment by cbellone** [comment]
Hi @gustavopinto,

I hope that my comments now are clearer than before.

Thank you,
Celestino

**Comment by gustavopinto** [comment]
Oh, very sorry. Now I see. I hope this is ok now @cbellone.

**Comment by cbellone** [comment]
Ready to be merged. Thank you, @gustavopinto !

**Pull request merged**
